import 'dart:developer' as developer;
import '../models/insight_model.dart';
import '../models/transaction_model.dart';
import '../models/behavior_prediction.dart';

class SupervisorService {
  SupervisorService._();
  static final SupervisorService instance = SupervisorService._();

  /// Validates and refines the output generated by the AdvisorService before it hits the UI.
  AdvisorMessage validateAndRefineAdvice({
    required AdvisorMessage rawAdvice,
    required double monthlyIncome,
    required TransactionModel? latestTransaction,
  }) {
    // Basic income checks
    if (monthlyIncome <= 0) {
      _logAction('Corrected due to missing/zero data context');
      return AdvisorMessage(
        id: rawAdvice.id,
        content: 'I need to know your monthly income to give accurate advice. You can update it in your profile.',
        isUser: rawAdvice.isUser,
        timestamp: rawAdvice.timestamp,
        type: AdvisorMessageType.text,
        status: SupervisorStatus.corrected,
        severity: AdviceSeverity.low,
        isVerified: true,
      );
    }

    if (latestTransaction != null) {
      final tAmount = latestTransaction.amount;
      
      // RULE 5: Extreme Values
      // If a single transaction is insanely high compared to income (e.g. 10x)
      if (tAmount > monthlyIncome * 10) {
         _logAction('Blocked due to extreme impossible value');
         return AdvisorMessage(
          id: rawAdvice.id,
          content: '❌ Financial logic locked.',
          reason: 'This transaction amount seems impossibly high or erroneous compared to your income profile.',
          actionSuggestion: 'Please delete or correct this transaction.',
          isUser: rawAdvice.isUser,
          timestamp: rawAdvice.timestamp,
          type: AdvisorMessageType.alert,
          severity: AdviceSeverity.high,
          status: SupervisorStatus.blocked,
          isVerified: true,
         );
      }

      // RULE 1: High Expense Detection (Overrides normal advice)
      if (tAmount > monthlyIncome * 0.45) {
        _logAction('Escalated to HIGH severity due to large transaction expense ratio');
        return AdvisorMessage(
          id: rawAdvice.id,
          content: '🔴 CRITICAL: Exceptional single expense detected.',
          reason: 'This transaction wiped out over 45% of your total monthly income.',
          actionSuggestion: 'Liquidate low-performing assets or pause SIPs if this causes a cash flow crisis.',
          isUser: rawAdvice.isUser,
          timestamp: rawAdvice.timestamp,
          type: AdvisorMessageType.alert,
          severity: AdviceSeverity.high,
          status: SupervisorStatus.corrected,
          isVerified: true,
        );
      }

      // RULE 2: Advisor Consistency (Conflict Resolution)
      // If ML says Good, but Advisor raw text generated an alert/warning
      if (latestTransaction.behaviorPrediction?.label == BehaviorLabel.good &&
          rawAdvice.type == AdvisorMessageType.alert) {
          
        _logAction('Conflict resolved: ML predicted Good, Advisor warned.');
        return AdvisorMessage(
          id: rawAdvice.id,
          content: 'This transaction triggered a structural warning, but aligns with your historical safe behavior.',
          reason: rawAdvice.reason,
          actionSuggestion: rawAdvice.actionSuggestion,
          isUser: rawAdvice.isUser,
          timestamp: rawAdvice.timestamp,
          type: AdvisorMessageType.text,
          severity: AdviceSeverity.medium,
          status: SupervisorStatus.corrected,
          isVerified: true,
        );
      }
    }

    // Default: Raw advice is logically safe and intact
    _logAction('Cleared and Verified raw advice flow');
    return AdvisorMessage(
      id: rawAdvice.id,
      content: rawAdvice.content,
      reason: rawAdvice.reason,
      actionSuggestion: rawAdvice.actionSuggestion,
      isUser: rawAdvice.isUser,
      timestamp: rawAdvice.timestamp,
      type: rawAdvice.type,
      severity: rawAdvice.severity,
      status: SupervisorStatus.valid,
      isVerified: true,
    );
  }

  void _logAction(String reason) {
     developer.log('[Supervisor] $reason', name: 'SupervisorAgent');
  }
}
