// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf9R8LZRgrrFqJqiJnHelmq1rYl4IVm20',
    appId: '1:479046921622:web:4a1dfd781d51e06eea41b7',
    messagingSenderId: '479046921622',
    projectId: 'muni-m',
    authDomain: 'muni-m.firebaseapp.com',
    storageBucket: 'muni-m.firebasestorage.app',
    measurementId: 'G-LFCS5CT9S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArHMGxkiI9jlIRU3kAWg_uyrx8V7A6Npo',
    appId: '1:479046921622:android:20296ceaf05448c1ea41b7',
    messagingSenderId: '479046921622',
    projectId: 'muni-m',
    storageBucket: 'muni-m.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJXv-Nfna46NF-NQREQ4nKEl1kv3bfzDk',
    appId: '1:479046921622:ios:a6115fc514a73bf6ea41b7',
    messagingSenderId: '479046921622',
    projectId: 'muni-m',
    storageBucket: 'muni-m.firebasestorage.app',
    iosBundleId: 'com.example.munim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJXv-Nfna46NF-NQREQ4nKEl1kv3bfzDk',
    appId: '1:479046921622:ios:a6115fc514a73bf6ea41b7',
    messagingSenderId: '479046921622',
    projectId: 'muni-m',
    storageBucket: 'muni-m.firebasestorage.app',
    iosBundleId: 'com.example.munim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf9R8LZRgrrFqJqiJnHelmq1rYl4IVm20',
    appId: '1:479046921622:web:b97ea2bf543c76caea41b7',
    messagingSenderId: '479046921622',
    projectId: 'muni-m',
    authDomain: 'muni-m.firebaseapp.com',
    storageBucket: 'muni-m.firebasestorage.app',
    measurementId: 'G-P176JCVB65',
  );
}
